name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Check if lint script exists
        id: check-lint
        run: |
          if grep -q '"lint"' package.json; then echo "exists=true" >> $GITHUB_OUTPUT; else echo "exists=false" >> $GITHUB_OUTPUT; fi
      - name: Run lint
        if: steps.check-lint.outputs.exists == 'true'
        run: npm run lint
      - name: Check if build script exists
        id: check-build
        run: |
          if grep -q '"build"' package.json; then echo "exists=true" >> $GITHUB_OUTPUT; else echo "exists=false" >> $GITHUB_OUTPUT; fi
      - name: Run tests
        run: npm test
      - name: Run build
        if: steps.check-build.outputs.exists == 'true'
        run: npm run build
