name: Publish on release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --omit=dev
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ secrets.GHCR_TOKEN != '' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.release.tag_name }}
      - name: Upload release.zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
